SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `evaluation_scores`;
DROP TABLE IF EXISTS `evaluations`;
DROP TABLE IF EXISTS `ai_prompt_tags`;
DROP TABLE IF EXISTS `ai_evaluation_prompts`;
DROP TABLE IF EXISTS `checklist_item_criteria`;
DROP TABLE IF EXISTS `evaluation_criteria`;
DROP TABLE IF EXISTS `evaluators`;
DROP TABLE IF EXISTS `llm_answers`;
DROP TABLE IF EXISTS `evaluation_runs`;
DROP TABLE IF EXISTS `llm_models`;
DROP TABLE IF EXISTS `dataset_question_mapping`;
DROP TABLE IF EXISTS `dataset_versions`;
DROP TABLE IF EXISTS `standard_question_tags`;
DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `standard_answer_checklist_items`;
DROP TABLE IF EXISTS `standard_subjective_answers`;
DROP TABLE IF EXISTS `standard_simple_answers`;
DROP TABLE IF EXISTS `standard_objective_answers`;
DROP TABLE IF EXISTS `crowdsourced_answers`;
DROP TABLE IF EXISTS `expert_candidate_answers`;
DROP TABLE IF EXISTS `standard_questions`;
DROP TABLE IF EXISTS `change_log_details`;
DROP TABLE IF EXISTS `change_log`;
DROP TABLE IF EXISTS `raw_answers`;
DROP TABLE IF EXISTS `raw_questions`;
DROP TABLE IF EXISTS `users`;

SET FOREIGN_KEY_CHECKS = 1; 