-- 更新变更日志系统中的change_type枚举值，添加CREATE_PROMPT_ASSEMBLY_CONFIG

-- 添加ANSWER_PROMPT_ASSEMBLY_CONFIG和EVALUATION_PROMPT_ASSEMBLY_CONFIG到entity_type枚举
ALTER TABLE `change_log_details` 
MODIFY COLUMN `entity_type` ENUM(
    'STANDARD_QUESTION', 
    'STD_OBJECTIVE_ANSWER', 
    'STD_SIMPLE_ANSWER', 
    'STD_SUBJECTIVE_ANSWER', 
    'TAG', 
    'DATASET_VERSION', 
    'LLM_MODEL', 
    'EVALUATOR', 
    'STANDARD_QUESTION_TAGS', 
    'DATASET_QUESTION_MAPPING', 
    'ANSWER_TAG_PROMPT', 
    'ANSWER_QUESTION_TYPE_PROMPT', 
    'EVALUATION_TAG_PROMPT', 
    'EVALUATION_SUBJECTIVE_PROMPT',
    'ANSWER_PROMPT_ASSEMBLY_CONFIG',
    'EVALUATION_PROMPT_ASSEMBLY_CONFIG'
) NOT NULL COMMENT '发生变更的实体类型';

-- 注意：实际上change_log表中的change_type字段是VARCHAR类型，不是ENUM类型
-- 这意味着它可以接受任意字符串，包括'CREATE_PROMPT_ASSEMBLY_CONFIG'
-- 因此，不需要修改change_log表结构，只需要确保代码中使用正确的常量 