-- 更新CHANGE_LOG_DETAILS表的ENTITY_TYPE枚举定义，添加缺少的枚举值
ALTER TABLE `CHANGE_LOG_DETAILS` 
MODIFY COLUMN `ENTITY_TYPE` ENUM(
    'STANDARD_QUESTION', 'STD_OBJECTIVE_ANSWER', 'STD_SIMPLE_ANSWER', 'STD_SUBJECTIVE_ANSWER',
    'STANDARD_OBJECTIVE_ANSWER', 'STANDARD_SIMPLE_ANSWER', 'STANDARD_SUBJECTIVE_ANSWER',
    'CHECKLIST_ITEM', 'EVAL_CRITERION', 'AI_PROMPT',
    'TAG', 'DATASET_VERSION', 'LLM_MODEL', 'EVALUATOR', 'STANDARD_QUESTION_TAGS',
    'DATASET_QUESTION_MAPPING', 'ANSWER_TAG_PROMPT', 'ANSWER_QUESTION_TYPE_PROMPT',
    'EVALUATION_TAG_PROMPT', 'EVALUATION_SUBJECTIVE_PROMPT',
    'ANSWER_PROMPT_ASSEMBLY_CONFIG', 'EVALUATION_PROMPT_ASSEMBLY_CONFIG',
    'AI_PROMPT_TAGS'
) NOT NULL COMMENT '发生变更的实体类型';

-- 如果上述ALTER TABLE语句执行失败，可以考虑使用以下替代方案：
-- 将ENTITY_TYPE列类型从ENUM改为VARCHAR，这样就不会受到枚举值限制
/*
ALTER TABLE `CHANGE_LOG_DETAILS` 
MODIFY COLUMN `ENTITY_TYPE` VARCHAR(50) NOT NULL COMMENT '发生变更的实体类型';
*/ 