server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 211418
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  http:
    encoding:
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8

# LLM API配置
llm:
  default-api-url: https://api.openai.com/v1/chat/completions
  default-model: gpt-3.5-turbo
  connection-timeout: 30 # 秒
  read-timeout: 60 # 秒
  retry:
    max-attempts: 3
    backoff-delay: 1000 # 毫秒

# 日志配置
logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 