server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: true

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 211418
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  messages:
    encoding: UTF-8
  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

# 异常处理配置
exception:
  handler:
    development-mode: true
    trace-enabled: true
    include-stacktrace-in-response: true
    detailed-error-messages: true

# AI服务配置
ai:
  service:
    url: https://api.openai.com/v1/chat/completions
    api-key: your-api-key-here
    model: gpt-3.5-turbo
    timeout: 60000

# LLM配置
llm:
  default-api-url: https://api.openai.com/v1/chat/completions
  default-model: gpt-3.5-turbo
  connection-timeout: 30
  read-timeout: 60
  retry:
    max-attempts: 3
    backoff-delay: 1000

# 日志配置
logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    com.example.demo.service.impl.EvaluationServiceImpl: INFO
    com.example.demo.exception: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30